apollographql/subscriptions-transport-ws

src/client.ts, src/test/tests.ts
Without this fix, if there are errors on the server side, the client will still run the `next(..)` handler on the client, instead of the `error(..)` handler.
This seems like a simple oversight, since the next block uses `payload.errors` correctly.
=> Fix typo in client-side SUBSCRIPTION_FAIL handling

package.json, src/server.ts, src/test/tests.ts
This is needed if we want to re-extract context from some async store (redis, dataloader, etc...)
=> Make the onSubscribe async

package.json, src/client.ts, typings.d.ts
Importing the complete lodash package is:
- heavy, we only need two functions here!
- side effects by changing the _ in the global scope (for example, someone using underscore in a legacy backbone app will be affected ;) )
=> Use specific lodash functions instead of package

src/client.ts, src/messageTypes.ts, src/server.ts, src/test/tests.ts
Some PAAS such as heroku limit the time a socket can stay open without sending anything. By adding the `keepAlive` option in the server's settings, you can now make sure the socket will stay open by sending empty keep alive packets in it from time to time.
`keepAlive` takes an amount of milliseconds as parameter and will yield an empty keep alive message each time this interval goes off.
=> Keep alive socket

src/server.ts, src/test/tests.ts
These two commits cover a couple more cases where a client sending invalid messages was crashing the server.
=> Prevent server crashes with incorrect clients

src/client.ts, src/server.ts, src/test/tests.ts
I noticed that is the `subscriptionManager.subscribe` threw a regular Error object the client received `undefined` despite the message type being `SUBSCRIPTION_FAIL` hence the introduction of `formatErrors`. The server was updated to check for `e.errors` and otherwise create a formatted error object.
=> improve error handling in server and client

package.json, src/client.ts, src/server.ts, src/test/tests.ts, typings.d.ts
This is an initial approach to handling having the client reconnect and resubscribe after losing its connection to the server. To enable this behavior a new `reconnect: true` option must be passed in to the constructor. Fixes #4 .
=> Client reconnection logic

src/server.ts, src/test/tests.ts
To use an object as a map with arbitrary keys, you should either use
`Object.create(null)` or the `Map` class.  Otherwise you can run into trouble
where keys like `toString` and `constructor` are in your app too.  If the server
received such a message, an exception would get thrown within
SubscriptionManager.unsubscribe.
Noticed while reviewing @Urigo 's PR
=> Don't throw in the server on certain unsub messages

README.md
=> Fix Docs to match implementation

README.md, package.json, src/helpers.ts, src/index.ts
Thought it may be time to add the missing `addGraphQLSubscriptions` helper function from the Subscriptions tutorial posted on [Medium](https://dev-blog.apollodata.com/graphql-subscriptions-in-apollo-client-9a2457f015fb#.7e9q6ir23) and linked here as an issue #38.
Code resides in a new `helper.ts`.
=> Added missing addGraphQLSubscriptions

CHANGELOG.md, package.json, src/client.ts, src/test/tests.ts
Hi, at Graphcool, we have the use case, that sometimes we want to send `data` AND `errors` on the `payload` of `SUBSCRIPTION_DATA` at the same time.
This is especially needed for our permissions system, where it could be that the requesting client is only allowed to see some fields on a query. In that case we don't want to disable all other fields, so we send the allowed fields and an error that explains why some fields are null.
This PR just makes sure, that if there is the `errors` property, `data` is not just nulled, but is actually checked if there is data.
=> Allow data and errors in payload of SUBSCRIPTION_DATA

CHANGELOG.md, package.json, src/client.ts, src/test/tests.ts
Currently, the `SUBSCRIPTION_START` is being sent before the `INIT` message.
In our case this results in `subscriptions-transport-ws` rejecting the `init_success` of the server.
This only happens in rare cases and I could barely reproduce this.
The environment that caused this problem looked like this:
- Slow connection
- Having 2 subscriptions in one application
- Using the `react-apollo` client
I'm not sure if the apollo client is responsible for the weird early `subscription_end`, but this is already a starting point.
Unfortunately, the test I added breaks 3 other Server related tests. Seems some async/concurrency issue, but I couldn't find out what exactly is causing it.
If it is ok for you, I also just can remove this test, as all other tests then still are green.
This is based on PR …
=> Send INIT before SUBSCRIPTION_START

src/client.ts, src/test/tests.ts
Guys ( @Urigo @DxCx @helfer @dotansimha @NeoPhi ) this pull request is a fix for the following situation:
1- Client connects to the server with `reconnect=true` to prevent for example temporary network failures.
2- Due to a necessary situation, for example a logout, the user of this package wants to close the client.
3- In this situation, even with `reconnect=true`, the `tryReconnect` method shouldn't be called.
=> feat(NA): force close without try reconnect

src/client.ts, src/middleware.ts, src/server.ts, src/test/tests.ts
Guys ( @Urigo @DxCx @helfer @dotansimha @NeoPhi ) this PR is to refact somethings that were introduced by #78 
However I also want to raise up the discussion about the middleware thing that @DxCx also comments on #78.
Do we wanna be able to use a middleware and always send the context over the network in every request? Isn't this a severe security issue? Won't we be able to accomplish the exact same use case described on #78 sent the authtoken in the connectionParams with the new `lazy` option enabled?
In my opinion this should't be released until we got a really good conclusion. However I haven't removed that in this PR, I had only refact somethings and also fixing a bug.
=> refact(NA): onsubscribe middleware pr

src/adapters/subscription-manager.ts
I noticed that the first subscription is never unsubscribed.
Turns out that the first operation id is zero and that the `if (opId) {`
check is the culprit.
Fixes: #180
TODO:
=> Don't skip opId === 0

CHANGELOG.md, src/helpers.ts, src/test/tests.ts, typings.d.ts
Importing from `lodash` loads the entire lib into memory unnecessarily.
=> chore(lodash): require specific lodash/assign module

CHANGELOG.md, README.md, src/client.ts, src/defaults.ts, src/test/tests.ts
@Urigo @dotansimha @DxCx 
This PR solves the following issue: usually when a backend receives a `connection_terminate` will invalidate the previous credentials so we should only send connection_terminate in a `forceClose`.
=> fix(NA): Non forced close without connection terminate and also some connection's flow improvements

CHANGELOG.md, README.md
By adjusting the `eventName` possible value to what they actually are.
TODO:
=> Fix on(eventName, cb, thisContext) readme doc

CHANGELOG.md, scripts/post-install.js
@Urigo @dotansimha @DxCx this is only a small fix so when installing from a branch it doesn't repeat the compile job for 2 times.
=> fix(NA): add a return after first post-install when it should install dev dependencies.

CHANGELOG.md, scripts/post-install.js
@Urigo  This is a small fix to only install dev dependencies if it is an install from branch situation.
=> fix(NA): on install from branch install dev dependencies only if dist folder isnt found.

CHANGELOG.md, src/server.ts
@Urigo @dotansimha @DxCx this small commits fixs a bug that I found in sequence of helping a user in the issue #220 . We should send the first KA message right after the connection ack in the server side.
=> fix(NA): send first keep alive message right after connection ack

CHANGELOG.md, src/server.ts, src/test/tests.ts
I've found out that server missed validation step.
Added it at the same API as Apollo-Server is:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-core/src/graphqlOptions.ts#L25
Closes #213 
TODO:
=> Add missing validation step

CHANGELOG.md, package.json, src/client.ts, src/test/tests.ts
This PR adds support for Apollo's ObservableNetworkInterface.
once Apollo version 2.0 is out, we should add integration with apollo-link,
however now it will be easier as the main function is already implemented.
Closes #201 
TODO:
=> Adds request interface to match apollo 2.0

CHANGELOG.md, src/client.ts
Small bugfix to make sure undefined callbacks won't be used.
=> Observer callbacks should be optional

CHANGELOG.md, src/server.ts, src/test/tests.ts
1. Exposes `server` for `noServer` configuration when user needs to emit `connection`.
2. add `close` method to disconnect all clients & remove connection hooks. (Closes #255)
=> chore: add close method to server

CHANGELOG.md, src/client.ts
@DxCx @Urigo @dotansimha this is a small fix for the close method.
=> fix(NA): gracefully unsubscribe to all pending operations before a requested close by the user

CHANGELOG.md, README.md
Add 2 examples for both `subscribe` and `subscribeToMore`.
`subscribeToMore` is not a function on apolloClient but working on a query result. Fix #265
`subscribe` need a subscriber for a full working example.
Both example were test with hybrid and Full WebSocket Transport.
TODO:
=> docs(README): Fix example for subscribe and subscribeToMore methods

src/server.ts, src/test/tests.ts
Fix a couple of typing changes required by latest typing files with TypeScript 2.5.X.
=> fix typings

src/message-types.ts
"This" in the top comment is a little unclear as it's unclear whether that comment refers to just the next message type or the entire block.
"Those" on the bottom comment is a little unclear as "those" is past tense, it could refer to the preceding message types.
TODO:
=> Made language a little clearer.

.npmignore, package.json, src/message-types.ts, src/server.ts, src/test/tests.ts
While updating our backend server to the latest version of this package we noticed backwards compatible issues with clients that were still on v1 of the protocol. These two fixes ensure that old clients get the deprecated keep alive message and that those messages are not sent until the client successfully establishes a connection (otherwise a keep alive of the wrong message type maybe sent).
TODO:
=> improved keep alive handling

CHANGELOG.md, src/server.ts
this fixes a bug that is similar to a bug found in [apollo-server](https://github.com/apollographql/apollo-server/pull/679)
Would be great to see this merged so we can use subscriptions
=> fix: context cloning for classes

src/server.ts
See: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it
This pull request resolved the warnings I received when using subscription-transport-ws with Bluebird installed as the global Promise object (`global.Promise = require('bluebird')`):
```
(node:17404) Warning: a promise was created in a handler at [REDACTED]/node_modules/subscriptions-transport-ws/src/server.ts:316:42 but was not
returned from it, see http://goo.gl/rRqMUw
at Function.Promise.cast (/[REDACTED]/node_modules/bluebird/js/release/promise.js:196:13)
at /[REDACTED]/node_modules/subscriptions-transport-ws/src/server.ts:316:42                                                                     at runCallback (timers.js:773:18)
at tryOnImmediate …
```
=> Fix: returning promises created in handlers

package.json
Currently this dependency throws an error with flowtype `v0.66`. A fix has been published to iterall `v1.2.1`
=> Updated dependency iterall to add support for flowtype v0.66

CHANGELOG.md, README.md, docs/source/lifecycle-events.md, src/server.ts, src/test/tests.ts
=> Pass request (upgradeReq) to ConnectionContext

CHANGELOG.md, README.md, src/defaults.ts
following the graphcool server setting. See: https://github.com/apollographql/subscriptions-transport-ws/issues/167
The problem described at https://www.graph.cool/forum/t/invoking-a-subscription-event-frequently-in-a-short-amount-of-time/1298/6?u=huan is not solved if the timeout is set to 10s.
TODO:
=> change default keep-alive setting from 10s to 30s

CHANGELOG.md, README.md, src/client.ts, src/test/tests.ts
**Use case:**
Writing simple (load)testing tools. At that moment there is no simple way to determinate connection errors. Also useful to debug network troubles.
**Could this be a plugin?**
No, we can't subscribe to ws error event directly.
**Is there a workaround?**
Save connection state(to check that connection closed by server) and catch `disconnected` event. But we don't have any error details.
=> Emit event when an websocket error occurs.

CHANGELOG.md, src/client.ts, src/test/tests.ts
=> Feature: inactivity timeout and tests

CHANGELOG.md, src/client.ts, src/test/tests.ts
Same patch as in https://github.com/apollographql/subscriptions-transport-ws/pull/428 but with test.
=> Fix duplicate subscription after reconnect

docs/source/setup.md
This updates all blog URLs in the documentation to use blog.apollographql.com
as the domain, rather than dev-blog.apollodata.com.
=> docs: Update blog URLs to reference blog.apollographql.com.

README.md, src/client.ts, src/test/tests.ts
Trying to solve pending #348 issues in order to allow to have `connectionParams` as a Promise.
=> Allow connectionParams as a Promise

CHANGELOG.md, README.md, docs/source/lifecycle-events.md, src/server.ts, src/test/tests.ts
Sometimes, the GraphQL schema needs to be dynamically resolved (e.g. when exposing a database interface). This change allows the schema to be provided either as a static value or as a function of the connection context:
```ts
const subscriptionServer = new SubscriptionServer(
{
schema: undefined,
onOperation: async (message, params, socket) => {
if (await something()) {
params.schema = schema1;
} else {
params.schema = schema2;
}
return params;
},
...
}
```
There are no tests for it since it's a fairly trivial change and I wasn't sure if it would be accepted, but I can write some smoke tests if required.
TODO:
=> Allow dynamic schema resolution 

CHANGELOG.md, src/client.ts, src/test/tests.ts
Hello,
I'm using the library on my front-end application and I would like to have the ability to set custom WebSocket protocols for client.
I've seen an existing issue with this feature request - that's why I'm opening this PR. Hope you'll like it!
TODO:
Resolves #404
=> Add ability to set custom WebSocket protocols in client

docs/source/setup.md, docs/source/subscriptions-to-schema.md
This branch updates two pages in the docs to use graphql syntax highlighting in the appropriate places
=> Use GraphQL syntax in codeblocks

.travis.yml, CHANGELOG.md, package.json, src/utils/empty-iterable.ts, tslint.json
Quick project tweaks:
- Bump `graphql` and `typescript` peer/dev deps
- Remove deprecated `tslint` rules
- Fix broken `src/utils/empty-iterable.ts` types
- Only run CI with Node 12
=> Bump graphql deps and fix broken tests/CI

CHANGELOG.md, src/client.ts, src/test/tests.ts, src/utils/empty-iterable.ts
=> fix: do not send GQL_STOP after GQL_COMPLETED is received

CHANGELOG.md, README.md, src/client.ts, src/defaults.ts
actually fix #295 completely
Does anyone care if I add tests for this?  It's not really "significant new logic"
TODO:
=> feat(client): add minTimeout option

CHANGELOG.md, src/client.ts
=> Clear WebSocket event listeners on close.

CHANGELOG.md, src/client.ts
TODO:
Two of the most used websocket node implementation both support 3rd or more arguments to the constructor. Referring to [ws doc](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) and [WebSocket-Node doc](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/W3CWebSocket.md#constructor)
This PR try adding an extra property to `ClientOptions` that can be used to pass extra arguments to the custom ws implementation.
=>  add option to pass extra websocket client arguments

CHANGELOG.md, src/server.ts
If `promisedParams` resolves to an exception then the error will be handled twice; once here:
https://github.com/apollographql/subscriptions-transport-ws/blob/34d503a6cef99efaffb35dae6a816ab898440565/src/server.ts#L418-L425
and once here:
https://github.com/apollographql/subscriptions-transport-ws/blob/34d503a6cef99efaffb35dae6a816ab898440565/src/server.ts#L430-L432
this PR resolves that issue. It's a very minor fix, so shouldn't require any test changes.
TODO:
=> Don't handle promisedParams error twice

CHANGELOG.md, PROTOCOL.md, README.md, src/client.ts, src/test/tests.ts
Sometimes, it's nice to send a payload with an ACK.
A good example might be a JWT, in case the one the client is using is about to expire.
Another example might be the app version, which allows you to upgrade the client without requiring a refresh (this pairs nicely with the built-in reconnect logic).
I think you guys were thinking about doing this, too, because I noticed a payload field for ACKs already exists in the tests: https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/test/tests.ts#L282
=> add optional payload to ACK

CHANGELOG.md, src/server.ts
The incorrect error was being returned instead of the one that was returned from `formatError`. This also supports https://github.com/apollographql/apollo-server/pull/2942.
TODO:
=> Destructure the correct error object

CHANGELOG.md, tsconfig.json
Changes proposed in this pull request:
- Inline sources contents in source map files. 
The current behavior is for `.map` files to refer to the source file. The issue is that the `src` directory is not part of the NPM package, which makes this package's source maps useless as they point to non-existent files. This causes a lot of warnings with `source-map-loader`.
This proposed change makes it so the content of source files gets inlined in the `.map` files, so there is no actual need to read the source files.
Another way to do this would be to bundle the `src` directory within the NPM package.
=> Inline sources contents in source map files

CHANGELOG.md, package.json
Note that there are breaking changes in `ws`
[`6.0.0`](https://github.com/websockets/ws/releases/tag/6.0.0) and
[`7.0.0`](https://github.com/websockets/ws/releases/tag/7.0.0); for example,
messages over 100MiB are rejected, and (in v7) the behavior of sending messages
while the connection is starting or ending has changed. We are publishing this
package to allow users of Apollo Server 2 to avoid seeing [this
CVE](https://www.npmjs.com/advisories/1748) in their `npm audit`. However, note
that (a) this CVE does not affect the subscriptions client, just the server
and (b) Apollo Server 3 will remove its superficial integration with this
package entirely. We encourage users of Apollo Server 2 to disable the
integration with this unmaintained package via `new ApolloServer({subscriptions: …
=> Bump `ws` dependency to allow v6 and v7.

CHANGELOG.md, package.json, src/server.ts, src/test/tests.ts
Support for `graphql@16` and bump minimal supported version to be `graphql@15.7.2`.
As part of this change signatures for `ExecuteFunction` and `SubscribeFunction` were changed.
=> Support for `graphql@16` and bump minimal supported version
