apollographql/subscriptions-transport-ws

src/test/tests.ts

The key change is adding a new test server that delays the response from onSubscribe. It also refactors some duplicated boilerplate code from the other test server instances being created and fixes whitespace in the test method.

delay the subscribe request to ensure the timeout fires, fixes #18

---

CHANGELOG.md
src/server.ts

Fixes #35
Adding a new test would have required to mock pubsub, didn't seem worth it.

Make unsubscribe work for id == 0

---

AUTHORS
LICENSE
README.md

Fixes #37.
Updated README with license & npm badges on the way
(license badge will only work when the change is merged)

Added license & authors files

---

CHANGELOG.md
src/server.ts
src/test/tests.ts

fix todo of handling runtime errors in server callback method

---

package.json
tsconfig.json

Fixed typings

---

CHANGELOG.md
src/client.ts

only attempt reconnect on a closed connection, fix for #70

---

.gitignore
CHANGELOG.md
package.json
webpack.config.js

Transpiling client.js to target browsers using webpack

---

README.md

// Create WebSocket client prefix url should be 'ws'

fix url websocket should prefix 'ws'

---

package.json

bugfix(package): allow nodejs client to import SubscriptionsClient

---

src/client.ts
src/server.ts
src/test/tests.ts

bugfix(handle-error): handle missing error inside init_fail message

---

src/client.ts
src/test/tests.ts

@DxCx @Urigo this PR contains the unit tests for the client side part of the new already merged protocol. It could be merged as the new requirements related by @Urigo in my other PR's comments will be made into the server side.

Client side tests for the new merged graphql transport ws protocol

---

CHANGELOG.md
src/server.ts
src/test/tests.ts

Handle 'error' event on server to prevent uncaught exceptions

---

CHANGELOG.md
src/client.ts
src/test/tests.ts

Guys ( @Urigo @DxCx @helfer @dotansimha @NeoPhi ) this PR enables the new connection events discussed in #136. 
No breaking change was introduced, however I coded some deprecation warnings.

feat(NA): add new connection events.

---

CHANGELOG.md
package.json
src/helpers.ts

Guys ( @dotansimha @DxCx @Urigo @NeoPhi ) this PR should close the issue #141

fix(NA): replace object.assign with lodash.assign to extend browser support

---

src/test/tests.ts

This PR here fixes some type checking errors on compiling the package.

test(NA): some fixes for test types on compile package.

---

README.md

Closes https://github.com/apollographql/subscriptions-transport-ws/issues/148

docs(README): fix docs

---

src/client.ts
src/test/tests.ts

Closes https://github.com/apollographql/subscriptions-transport-ws/issues/161

Fix for reconnect after manual close

---

CHANGELOG.md
src/client.ts
src/helpers.ts
src/test/tests.ts

Related to:
https://github.com/apollographql/subscriptions-transport-ws/issues/173
https://github.com/apollographql/subscriptions-transport-ws/issues/149

feat(string-key): change subscription key to be string instead of number

---

CHANGELOG.md
README.md
src/defaults.ts

Closes https://github.com/apollographql/subscriptions-transport-ws/issues/167

Increase default timeout to 30s, and updated README timeout docs

---

CHANGELOG.md
src/client.ts
src/server.ts

@Urigo @DxCx @dotansimha this should fix the complete flow for an operation.

fix(NA): call operation handler before delete the operation on operation complete

---

README.md

docs(NA): Fix typo in README

---

CHANGELOG.md
README.md

Fix typo error on example.
TODO:

docs(README): Fix options example for subscribe methods

---

CHANGELOG.md
package.json

Prepare for release of 0.9.1 version.

chore(NA): update changelog and version package to prepare for relesae.

---

.npmignore
CHANGELOG.md
package.json

prep-0.9.2

---

CHANGELOG.md
docs/source/setup.md

Not sure if I updated CHANGELOG.md correctly. Just let me know if I need to change anything.

Fix dead link in setup.md

---

docs/source/external-pubsub.md

add link to Google PubSub implementation

---

CHANGELOG.md
package.json

Preps v0.9.7 with the recent changes

prep v0.9.7

---

docs/package.json
renovate.json

Remove renovate config from nested package.json

---

docs/source/authentication.md

Also some minor grammatical fixes.

Fix link to React example

---

README.md

Fix constructor signature

---

docs/.gitignore
docs/gatsby-config.js
docs/package-lock.json
docs/package.json
docs/static/_redirects
netlify.toml

This branch moves this repo's docs from Hexo to Gatsby using our new theme

Move docs from Hexo to Gatsby

---

docs/package-lock.json
docs/package.json

This branch updates the Gatsby docs theme

Upgrade gatsby theme for GA and github link fixes

---

docs/package-lock.json
docs/package.json

This branch upgrades the theme to get GA working properly

Upgrade theme for another GA fix

---

docs/gatsby-config.js
docs/package-lock.json
docs/package.json
docs/source/authentication.md
docs/source/express.md
docs/source/index.mdx
docs/source/setup.md
docs/source/subscriptions-to-schema.md
netlify.toml

This branch upgrades the docs theme to v1

Upgrade docs theme

---

CHANGELOG.md
src/index.ts

Fixes https://github.com/apollographql/subscriptions-transport-ws/issues/412
TODO:

Fix message-types export

---

CHANGELOG.md
src/server.ts

Fix wrong console.error for formatResponse

---

docs/source/authentication.md

[DOCS] Fix subscription example link

---

docs/source/express.md

Update valid usage of apollo-server-express package from package's latest docs:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-express/README.md
TODO:
- n/a Make sure all of the significant new logic is covered by tests
- n/a Rebase your changes on master so that they can be merged easily
- n/a Make sure all tests and linter rules pass
- n/a Update CHANGELOG.md with your change

Fix example of apollo-server-express usage
